import pytest
import datetime
import signal
import time
import threading


from engine_tools import scheduler_async

tmo = 2


@pytest.mark.timeout(tmo)
def test_single_count_blocking(counter_class):
    z = scheduler_async.EventMgr(
        datetime.timedelta(seconds=.01),
        end=datetime.datetime.now() + datetime.timedelta(seconds=.1),
        block=True,
        task = counter_class.task
    )
    z.start()
    assert counter_class.count == 10, "improper # of runs for given duration"


@pytest.mark.timeout(tmo)
def test_single_count_non_blocking(counter_class):
    z = scheduler_async.EventMgr(
        datetime.timedelta(seconds=.01),
        end=datetime.datetime.now() + datetime.timedelta(seconds=.1),
        block=False,
        task = counter_class.task
    )
    z.start()
    time.sleep(.5)
    assert counter_class.count == 10, "improper # of runs for given duration"

@pytest.mark.timeout(tmo)
def test_block_exception_ending(limited_counter_class):
    z = scheduler_async.EventMgr(
        datetime.timedelta(seconds=.01),
        end=datetime.datetime.now() + datetime.timedelta(seconds=1),
        block=True,
        task = limited_counter_class.task
    )
    z.start()
    assert limited_counter_class.count == 50, "did not cease at error"


@pytest.mark.timeout(tmo)
def test_no_block_exception_ending(limited_counter_class):
    z = scheduler_async.EventMgr(
        datetime.timedelta(seconds=.01),
        end=datetime.datetime.now() + datetime.timedelta(seconds=1),
        block=False,
        task = limited_counter_class.task
    )
    z.start()
    time.sleep(1)
    assert limited_counter_class.count == 50, "did not cease at error"

@pytest.mark.timeout(tmo)
def test_block_exception_ending_no_duration(limited_counter_class):
    z = scheduler_async.EventMgr(
        datetime.timedelta(seconds=.01),
        block=True,
        task = limited_counter_class.task
    )
    z.start()
    assert limited_counter_class.count == 50, "did not cease at error"


@pytest.mark.timeout(tmo)
def test_no_block_exception_ending_no_duration(limited_counter_class):
    z = scheduler_async.EventMgr(
        datetime.timedelta(seconds=.01),
        block=False,
        task = limited_counter_class.task
    )
    z.start()
    time.sleep(1)
    assert limited_counter_class.count == 50, "did not cease at error"


'''
@pytest.mark.timeout(tmo)
def test_non_blocking_sigterm(limited_counter_class):
    z = scheduler_async.EventMgr(
        datetime.timedelta(seconds=.01),
        end=datetime.datetime.now() + datetime.timedelta(seconds=1),
        block=False,
        task = limited_counter_class.task
    )
    z.start()
    time.sleep(.1)
    signal.pthread_kill(threading.get_ident(),signal.SIGTERM)
    assert limited.counter_class.count < 10 
'''
   
    
